/// GENERATED BY assets_scanner. DO NOT MODIFY BY HAND.
/// See more detail on https://github.com/littleGnAl/assets-scanner.
class MainAssets {
  static const package = 'cozy_house';

  static const Icon_love_solid = 'assets/Icon_love_solid.svg';

  static const splash_home = 'assets/splash_home.png';

  static const btn_wishlist = 'assets/btn_wishlist.svg';

  static const ic_bed = 'assets/ic_bed.svg';

  static const ic_start = 'assets/ic_start.svg';

  static const r_404 = 'assets/404.svg';

  static const ic_kitchen = 'assets/ic_kitchen.svg';

  static const Icon_love = 'assets/Icon_love.svg';

  static const Icon_mail = 'assets/Icon_mail.svg';

  static const Icon_card_solid = 'assets/Icon_card_solid.svg';

  static const Icon_card = 'assets/Icon_card.svg';

  static const ic_lemari = 'assets/ic_lemari.svg';

  static const Icon_home = 'assets/Icon_home.svg';

  static const Icon_mail_solid = 'assets/Icon_mail_solid.svg';

  static const logo = 'assets/logo.svg';

  static const ic_mark = 'assets/ic_mark.svg';

  static const Icon_home_solid = 'assets/Icon_home_solid.svg';

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new,public_member_api_docs,constant_identifier_names,prefer_double_quotes
}
