/// GENERATED BY assets_scanner. DO NOT MODIFY BY HAND.
/// See more detail on https://github.com/littleGnAl/assets-scanner.
class MainAssets {
  static const package = 'cozy_house';

  static const splash_home = 'assets/splash_home.png';

  static const btn_wishlist = 'assets/btn_wishlist.svg';

  static const ic_bed = 'assets/ic_bed.svg';

  static const ic_start = 'assets/ic_start.svg';

  static const r_404 = 'assets/404.svg';

  static const ic_kitchen = 'assets/ic_kitchen.svg';

  static const ic_lemari = 'assets/ic_lemari.svg';

  static const logo = 'assets/logo.svg';

  static const ic_mark = 'assets/ic_mark.svg';

  static const ic_mail = 'assets/ic_mail.svg';

  static const ic_card = 'assets/ic_card.svg';

  static const ic_home = 'assets/ic_home.svg';

  static const ic_love = 'assets/ic_love.svg';

  static const bandung = 'assets/bandung.jpg';

  static const guidance = 'assets/guidance.svg';

  static const jakarta = 'assets/jakarta.jpg';

  static const surabaya = 'assets/surabaya.jpg';

  static const guidance1 = 'assets/guidance1.svg';

  static const r_4 = 'assets/4.jpg';

  static const r_5 = 'assets/5.jpg';

  static const r_6 = 'assets/6.jpg';

  static const r_2 = 'assets/2.jpg';

  static const r_3 = 'assets/3.jpg';

  static const r_1 = 'assets/1.jpg';

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new,public_member_api_docs,constant_identifier_names,prefer_double_quotes
}
